
// DO NOT EDIT, this file is generated by Firebase Studio
import {initializeApp, getApp, getApps, FirebaseApp} from 'firebase/app';
import {getAuth, connectAuthEmulator} from 'firebase/auth';
import {getFirestore, connectFirestoreEmulator} from 'firebase/firestore';

const firebaseConfig = {
  apiKey: 'fake-api-key',
  authDomain: 'fake-auth-domain-11542.firebaseapp.com',
  projectId: 'fake-project-id-11542',
  storageBucket: 'fake-project-id-11542.appspot.com',
  messagingSenderId: '1234567890',
  appId: '1:1234567890:web:abcdef1234567890',
};

let firebaseApp: FirebaseApp;

if (!getApps().length) {
  firebaseApp = initializeApp(firebaseConfig);
} else {
  firebaseApp = getApp();
}

const auth = getAuth(firebaseApp);
const firestore = getFirestore(firebaseApp);

// Check for development environment and connect to emulators if available.
// Note: The emulators must be running for this to work.
if (typeof window !== 'undefined') {
  // Point to the emulators for local development.
  connectAuthEmulator(auth, 'http://localhost:9099', { disableWarnings: true });
  connectFirestoreEmulator(firestore, '127.0.0.1', 8080);
}

export {firebaseApp, auth, firestore};
